# Python for Data Science
- Python is an open source general-purpose coding language, it was created by Guido van Rossum and first released in 1991
- Python is a beginner-friendly language, python code syntax uses English keywords, that makes it easy for anyone to understand and get started with the language


**What we cover:**
1. Python Arithmetic Operators
2. Python Logical Operators
3. Python Variables
4. Python Built-in Functions
5. Python Data Types (Data Structures)
6. Python Data Types Deep Dive
    - Lists
    - Tuples
    - Sets
    - Dictionaries
    - String
7. Python If/else conditions
8. Python Loops
    - For Loop
    - While Loop
9. Python Open function & With Open function

## Python Arithmetic Operators
Common Arithmetic operators supported by python:

| Operator | Description   |
|:- |:- |
|+	|Addition|
|-	|Subtraction|
|*	|Multiplication|
|/	|Division|
|%	|Modulus|
|**	|Exponentiation|
|//	|Floor division|

In [98]:
# Addition
print(7 + 10)

# Concatenate strings
print("I'm" + " " + "James")

# Subtraction
print(8 - 5)

# Multiplication
print(2 * 5)

# Division
print(8 / 5)

# Modulus - returns the remainder after a division
print(8 % 5)

# Floor division - rounds the result down to the nearest whole number
print(10 // 3)

# Exponentiation - Performs a exponential (power) calculation
# 2 to the power of 3 --> 2 x 2 x 2 = 8
print(2 ** 3)

17
I'm James
3
10
1.6
3
3
8


#### Question

Suppose you have £50, which you want to invest with a 20% return each year, for 8 years.

- After 1  year  --> 50 × 1.2       = 60
- After 2 years --> 50 × 1.2 × 1.2 = 72
- After 3 years --> 50 × 1.2 × 1.2 × 1.2 = 86.4
- .....
- .....

Add code below to calculate how much money you end up having after 8 years?

In [99]:
# Write down the answer here:

print(50 * 1.2 ** 8)

214.99084799999991


## Python Logical Operators
- In python logical operators are used while constructing conditional statements
- The result of a Logical operation is always a Ture or False

| Operator | Description   |
|:- |:- |
|<	|Less than	|
|<=	|Less than or equal to|
|==	|Equal|	
|>	|Greater than|	
|>=	|Greater than or equal to|
|!=	|Not equal|	
|and| 	Returns True if both statements are true|
|or	|Returns True if one of the statements is true|
|not|	Reverse the result, returns False if the result is true|

In [100]:
# Logical operators on numerical data
print(1000 < 2000)        #Less than
print(1000 <= 2000)       #Less than or equal to
print(1000 == 1000)       #Equal
print(1000 > 2000)        #Greater than
print(1000 >= 2000)       #Greater than or equal to
print(1000 != 2000)       #Not equal

True
True
True
False
False
True


In [101]:
# Logical operators on string data
print("Data" == "data")   #Equal
print("Data" != "data")   #Not equal

False
True


In [102]:
# AND, OR , NOT logical operators - These operators are used to combine multiple conditions

# Returns True if both statements are true
print(1000 < 2000 and 3000 < 4000)
print(1000 < 2000 and "Data" == "Data")  

# Returns True if one of the statements is true
print(1000 < 2000 or 3000 < 4000)
print(1000 < 2000 or "Data" == "Data")  

# Reverse the result, returns False if the result is true
print(not 1000 < 2000)

True
True
True
True
False


## Python Variables
- A variable is a named memory location used to store data values
- It is a container that holds data that can be referred to later
- Assignment operator needs to be used while creating a variable

**Various assignment operators**

| Operator | Description   | Result|
|:- |:- |:- |
|=	|x = 10	|x = 10|	
|+=	|x += 10	|x = x + 10|	
|-=	|x -= 10	|x = x - 10|	
|*= |x *= 10	|x = x * 10|

In [103]:
name = "James"   # A string assignment
age = 25         # An integer assignment
height = 1.8     # A float assignment
weight = 75      # A float assignment

print(name)
print(age)
print(height)
print(weight)

James
25
1.8
75


#### Question

Add the code below to calculate the **Body Mass Index**?

![bmi](pics/bmi.png)

In [104]:
# Calculate Body Mass Index (BMI) for James
# Save the calculation into variable "bmi"
# Write down the answer here:

bmi = weight/height**2
print(bmi)

23.148148148148145


In [105]:
# Convert James’s hight into feet (1 foot is exactly 0.3048 meters)
# Save the calculation into variable “heightf”
# Write down the answer here:

heightf = height / 0.3048
print(heightf)

5.905511811023622


## Python Built-in Functions

Python has several built-in functions that are readily available for use

For example the  **max()** function which returns the largest value of a given set of data values. \
These functions make the life of a programmer easier as many codes and task have already been defined in these functions.

| Function | Description   |
|:- |:- |
|   **type()**  | Returns the type of an object|
|   **print()**  | Prints the given object|
|   **len()**  | Returns the length of an object (only works on sequences)|
|   **sorted()**  | Returns a sorted list (only works with sequences)|
|   **min()**  | Returns the smallest item in an iterable|
|   **max()**  | Returns the largest item in an iterable|
|   **abs()**  | Returns the absolute value of a number|
|   **round()**  | Rounds a numbers|
|   **range()**  | Return a sequence of integers between start and stop values (default increments is by 1)|
|   **sum()**  | Return the Sum of the items|

<br><br>


- Several built-in functions that can be used for data-type conversions, this is also referred to as **casting**, following are some common casting functions in python

| Function | Description   |
|:- |:- |
|   **str()**  | Returns the string version of the object|
|   **int()**  | Returns integer from a number or string|
|   **float()**  | Returns floating point number from number, string|
|   **bool()**  | Converts a data value to Boolean|

<br><br>

#### Some useful references:

[Python Built-in Functions](https://docs.python.org/3/library/functions.html)

[Math functions from Math library](https://docs.python.org/3/library/math.html#module-math)

In [106]:
# Calculating the minimum value in a number series
min([122.8,45.7,5,63])

5

In [107]:
# Sorting the values in a number series
sorted([122.8,45.7,5,63])

[5, 45.7, 63, 122.8]

In [108]:
# Converting a numerical value to a string
str(28)

'28'

In [109]:
# Converting a string value to an integer
int("5")

5

In [110]:
# Converting a numerical value to a float
float(8)

8.0

In [111]:
# Converting a numerical value to a string
bool(0)

False

In [112]:
# Question
# Calculate the total of the numerical values [122.8,45.7,5,63] and round-up to the nearest whole number

sum([122.8,45.7,5,63])
round(sum([122.8,45.7,5,63]))

236

In [113]:
# Question
# [122.8,45.7,5,63] - Sort the numerical values in descending order

sorted([122.8,45.7,5,63], reverse=True)

[122.8, 63, 45.7, 5]

## Python Data Types
- Every data value in Python has a data type
- Every data value/variable in python is an object
- Use the **type()** function to determine which class a data value or a variable belongs to 

#### Python has the following data types:

- Numeric Types (Numbers): **int, float, complex**
- Sequence Types (indexed/ordered values): **list, tuple, range**
- Text Type (strings/characters/Sequence): **str**
- Mapping Type (key-value pairs): **dict**
- Boolean Type (for True/False): **bool**
- Set Types (Union/Intersection): **set**

![data types](pics/datatypes.png)

# Python Data Types Deep Dive
- Lists
- Tuples
- Sets
- Dictionaries
- Strings

## Lists  

- List is one of the most frequently used and very versatile data types used in Python 
- List is an **mutable(changeable)** ordered sequence of items
- In Python a list is created by placing all the items inside **square brackets [ ]**, separated by commas
- List can contain any number of items with different data types (integer, float, string etc.)


In the following section we'll be looking at, 
- How to create python lists
- Subsetting or Slicing Python Lists
- Negative Indexing
- Updating/Changing items in a list
- Python List Methods

#### Python uses zero indexing technique
- Python indexing starts with **0** as the first position/element
- To access any item in the sequence its index can be used

![list](pics/pythonlist.png)

In [114]:
# List of integers
mylist = [12, 58, 23, 77, 105, 84]
print(mylist)
type(mylist)

[12, 58, 23, 77, 105, 84]


list

In [115]:
# List of strings
mylist = ["avocado", "mango", "orange", "banana", "apple", "cherry"]
print(mylist)
type(mylist)

['avocado', 'mango', 'orange', 'banana', 'apple', 'cherry']


list

In [116]:
# List with mixed data types
mylist = ["Dan", 54, "SQL", "Python", 3.4, True]
print(mylist)
type(mylist)

['Dan', 54, 'SQL', 'Python', 3.4, True]


list

In [117]:
# A List can also have another list as an item
# This type of list is called as a nested list
results = [["Sam",87],["Tom",94],["Adam",74]]
print(results)
type(results)

[['Sam', 87], ['Tom', 94], ['Adam', 74]]


list

In [118]:
# List Length - To determine how many items a list has, use the len() function:
mylist = ["avocado", "mango", "orange", "banana", "apple", "cherry"]
len(mylist)

6

#### Question

![list](pics/pandas_series_design.png)

 - Write down the code to design the above list data structure
 - Save the list as "agelist1"
 - also determine the length of the list

In [119]:
# Write down the answer here:

agelist1 = [22, 15, 28, 43, 30, 8, 65]
print(agelist1)
type(agelist1)

[22, 15, 28, 43, 30, 8, 65]


list

#### Question

![stocklist](pics/stocklist.png)

 - Write down the code to design the above nested list data structure
 - Save the list as "stocklist1"

In [120]:
# Write down the answer here:

stocklist1 = [["AMZN",3100],["TSLA",560],["MSFT",215],["AAPL",120]]
print(stocklist1)
type(stocklist1)

[['AMZN', 3100], ['TSLA', 560], ['MSFT', 215], ['AAPL', 120]]


list

## Subsetting or Slicing Python Lists
- you can access a list item by referring to an index number
- you can use the index operator **"[ ]"** to access an item in a list
- In Python indices starts from 0

for example, a list having 6 items will have an index from 0 to 5

![list](pics/pythonlist.png)

In [121]:
mylist = ["avocado", "mango", "orange", "banana", "apple", "cherry"]

print(mylist[0])
print(mylist[1])
print(mylist[2])

avocado
mango
orange


## Negative Indexing
- Python allows negative indexing for its sequences
- Negative indexing means beginning from the end
- The index of -1 refers to the last item, -2 to the second last item and so on

![Negative Index](pics/pythonlistnegativeindex.png)

In [122]:
mylist = ["avocado", "mango", "orange", "banana", "apple", "cherry"]
print(mylist[-1])
print(mylist[-6])

cherry
avocado


#### Question
![stocklist](pics/stocklist.png)

 - Refer to the above "stocklist1"
 - Write down the code to extract the ["TSLA",560] from the nested list data structure
 - Use both Indexing and Negative-indexing techniques

In [123]:
# Write down the answer here:
stocklist1 = [["AMZN",3100],["TSLA",560],["MSFT",215],["AAPL",120]]

stocklist1[1]
stocklist1[-3]

['TSLA', 560]

## Accessing Range of items

- you can access a range of items in a list by using the **(:)** colon operator
- The start index will be included, while the end index is not

![range](pics/slicing.png)

In [124]:
mylist = ["avocado", "mango", "orange", "banana", "apple", "cherry"]

#Returns second and third items only - The start index will be included, while the end index is not
print(mylist[2:4])

#Returns second, third and fourth items only - The start index will be included, while the end index is not
print(mylist[2:5])

['orange', 'banana']
['orange', 'banana', 'apple']


#### Question

![stocklist](pics/stocklist.png)

 - Refer to the above "stocklist1"
 - Write down the code to extract the ["TSLA",560] and ['MSFT', 215] from the nested list data structure

In [125]:
# Write down the answer here:
stocklist1 = [["AMZN",3100],["TSLA",560],["MSFT",215],["AAPL",120]]

stocklist1[1:3]

[['TSLA', 560], ['MSFT', 215]]

## Updating/Changing items in a list
- Lists are mutable, meaning their items can be changed (unlike string or tuple)
- We can use the assignment operator (**=**) to change an item or a range of items
- To change the value of a specific item, refer to the index number

In [126]:
mylist = ["avocado", "mango", "orange", "banana", "apple", "cherry"]
mylist[1] = "peach"
print(mylist)

['avocado', 'peach', 'orange', 'banana', 'apple', 'cherry']


#### Question

![stocklist](pics/stocklist.png)

 - Refer to the above "stocklist1"
 - Write down the code to update TSLA price from 560 to 600

In [127]:
# Write down the answer here:
stocklist1 = [["AMZN",3100],["TSLA",560],["MSFT",215],["AAPL",120]]

stocklist1[1][1] = 600
stocklist1

[['AMZN', 3100], ['TSLA', 600], ['MSFT', 215], ['AAPL', 120]]

## Python List Methods

- Python has set of built-in methods that are available with every list object
- They are accessed as **list.method()**

| Method | Description   |
|:- |:- |
|   append()  | Adds an item to the end of the list|
|   clear()  | Removes all items from the list|
|   copy()  | creates a new copy of the current list|
|   count()  | Returns the count of the number of items passed as an argument|
|   extend()  | Add all items of a list to the end of another list|
|   index()  | Returns the index of the first item with the specified value|
|   insert()  | Adds an item at the specified index position|
|   pop()  | Removes an item from the list at the given index|
|   remove()  | Removes the item with the specified value|
|   reverse()  | Reverses the order of the list|
|   sort()  | Sorts the list|

<br><br><br><br>

#### Some useful references:

[Python List Methods](https://docs.python.org/3/tutorial/datastructures.html)

[Python List Methods](https://www.w3schools.com/python/python_ref_list.asp)

#### Python List append() method
- The append() method adds an item to the end of the list

In [128]:
fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits)

['apple', 'banana', 'cherry', 'orange']


#### Python List clear() method
- The clear() method removes all items from the list

In [129]:
fruits = ["apple", "banana", "cherry"]
fruits.clear()
print(fruits)

[]


#### Python List copy() method
- The copy() method returns a new copy of the current list
- In Python a new list can not be copied by simply typing list2 = list1, for this copy() method needs to be used

In [130]:
fruits = ["apple", "banana", "cherry"]
mylist = fruits.copy()
print(mylist)

['apple', 'banana', 'cherry']


#### Python List count() method
- The count() method returns the number of times the specified item appearing in the list
- This is a type of a pattern match technique

In [131]:
fruits = ["apple", "banana", "cherry", "banana"]

fruits.count("banana")

2

#### Python List extend()
- The extend() method adds all items from a specified list to the end of the current list

In [132]:
fruits  = ["apple", "banana", "cherry"]
results = [70, 80, 90]

fruits.extend(results)
print(fruits)

['apple', 'banana', 'cherry', 70, 80, 90]


#### Python List index()
- The index() method returns the index of the specified item in the list

In [133]:
fruits = ["apple", "banana", "cherry"]

fruits.index("cherry")

2

#### Python List insert()
- The insert() method adds an item at the specified index position

In [134]:
fruits = ["apple", "banana", "cherry"]

fruits.insert(1, "orange")

print(fruits)

['apple', 'orange', 'banana', 'cherry']


#### Python List pop()
- The pop() method removes an item from the list at the given index and returns the removed item

In [135]:
fruits = ["apple", "banana", "cherry"]

fruits.pop(1)

'banana'

#### Python List remove()
- The remove() method removes the first matching item (which is passed as an argument) from the list

In [136]:
fruits = ["apple", "banana", "cherry","banana"]

fruits.remove("banana")

print(fruits)

['apple', 'cherry', 'banana']


#### Python List reverse()
- The reverse() method reverses the order of the list

In [137]:
fruits = ["apple", "banana", "cherry"]

fruits.reverse()

print(fruits)

['cherry', 'banana', 'apple']


#### Python List sort()
- The sort() method sorts the items in the list in either ascending or descending order

In [138]:
#Sort the list ascending:

cars = ["Ford", "BMW", "Toyota", "Volkswagen"]

cars.sort()

print(cars)

['BMW', 'Ford', 'Toyota', 'Volkswagen']


In [139]:
#Sort the list descending:

cars = ["Ford", "BMW", "Toyota", "Volkswagen"]

cars.sort(reverse=True)

print(cars)

['Volkswagen', 'Toyota', 'Ford', 'BMW']


#### Question

![stocklist](pics/stocklist2.png)

 - Refer to the "stocklist1"
 - Append ['GOOGL', 1800] to the list, and remove ['AMZN', 3100] from the list

In [140]:
# Write down the answer here:
stocklist1 = [["AMZN",3100],["TSLA",600],["MSFT",215],["AAPL",120]]

stocklist1.append(["GOOGL", 1800])
stocklist1.remove(["AMZN", 3100])
print(stocklist1)

[['TSLA', 600], ['MSFT', 215], ['AAPL', 120], ['GOOGL', 1800]]


## Tuples
- Tuple is similar to a list in terms of indexing
- Tuple is an **immutable(unchangeable)** ordered sequence of items, meaning items inside a Tuple can not be changed/updated
- In Python a tuple is created by placing all the items inside **parentheses ( )**, separated by commas
- Tuple can contain any number of items with different data types (integer, float, string etc.)


![tuple](pics/tuple.png)

In [141]:
# tuple of integers
mytuple = (12, 28, 37)
print(mytuple)
type(mytuple)

(12, 28, 37)


tuple

In [142]:
# tuple of strings
mytuple = ("avocado", "mango", "orange", "banana", "apple")
print(mytuple)
type(mytuple)

('avocado', 'mango', 'orange', 'banana', 'apple')


tuple

In [143]:
# tuple with mixed data types
mytuple = (1, "apple", 3.4, True)
print(mytuple)
type(mytuple)

(1, 'apple', 3.4, True)


tuple

In [144]:
# A tuple can also have another tuple as an item
# This type of tuple is called as a nested tuple
results = (("Sam",87),("Tom",94),("Adam",74))
print(results)
type(results)

(('Sam', 87), ('Tom', 94), ('Adam', 74))


tuple

In [145]:
# Tuple Length - To determine how many items a tuple has, use the len() function:
mytuple = ("avocado", "mango", "orange", "banana", "apple")
len(mytuple)

5

#### Question

![tuple](pics/pandas_series_design.png)

 - Write down the code to design the above tuple data structure
 - Save the list as "agetuple1"
 - also determine the length of the tuple

In [146]:
# Write down the answer here:

agetuple1 = (22, 15, 28, 43, 30, 8, 65)
print(agetuple1)
type(agetuple1)

(22, 15, 28, 43, 30, 8, 65)


tuple

#### Question

![stocktuple](pics/stocklist.png)

 - Write down the code to design the above nested tuple data structure
 - Save the list as "stocktuple1"

In [147]:
# Write down the answer here:

stocktuple1 = (("AMZN",3100),("TSLA",560),("MSFT",215),("AAPL",120))
print(stocktuple1)
type(stocktuple1)

(('AMZN', 3100), ('TSLA', 560), ('MSFT', 215), ('AAPL', 120))


tuple

## Subsetting or Slicing Python tuple

In [148]:
mytuple = ("avocado", "mango", "orange", "banana", "apple", "cherry")
print(mytuple[1])
print(mytuple[-4])

mango
orange


## Accessing Range of items

- you can access a range of items in a tuple by using the **(:)** colon operator
- The start index will be included, while the end index is not

![range](pics/slicing.png)

In [149]:
mytuple = ("avocado", "mango", "orange", "banana", "apple", "cherry")

#Returns second and third items only - The start index will be included, while the end index is not
print(mytuple[2:4])

#Returns second, third and fourth items only - The start index will be included, while the end index is not
print(mytuple[2:5])

('orange', 'banana')
('orange', 'banana', 'apple')


## Python Tuple Methods

- Python has set of built-in methods that are available with every tuple object
- They are accessed as **tuple.method()**

| Method | Description   |
|:- |:- |
|count()|Returns the number of times a specific value occurs in a tuple|
|index()|Searches the tuple for a specific value and returns the position of where the value was found|


<br><br><br><br><br>

#### Some useful references:

[Python Tuple Methods](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)

[Python Tuple Methods](https://www.w3schools.com/python/python_ref_tuple.asp)

## Sets
- A set is an unordered and unindexed collection of items, without any duplicate items. In a set every item is unique (no duplicates)
- A set is created by placing all the items/elements inside **curly braces { }**, separated by commas
- It is also possible to use the set() constructor to make a set, this is useful when converting a list/tuple to a set
- A sets can also be used to perform mathematical set operations like union, intersection, etc
- A set can contain any number of items with different data types (integer, float, string, etc..)


![set](pics/set.png)


### Sets vs Lists and Tuples
- Lists and tuples store values in a sequence (ordered and indexed)
- sets unlike lists or tuples, cannot have multiple occurrences of the same element and store unordered values

### Practical Use Cases of Python Sets
Because sets cannot have multiple occurrences of the same item/element, sets are highly useful while removing duplicate values from a list or tuple, and also while performing common math operations like unions, intersections, etc.


In [150]:
# set of integers
myset = {92, 56, 12, 28, 37}
print(myset)
type(myset)

{37, 12, 92, 56, 28}


set

In [151]:
# set of strings
myset = {"avocado", "mango", "orange", "banana", "apple"}
print(myset)
type(myset)

{'banana', 'mango', 'orange', 'avocado', 'apple'}


set

In [152]:
# set with mixed data types
myset = {1, "apple", 3.4, True}
print(myset)
type(myset)

{'apple', 1, 3.4}


set

In [153]:
# set cannot have duplicate items/elements
myset = {7, 7, 1, 2, 2, 3, 4, 3, 2}
print(myset)

{1, 2, 3, 4, 7}


In [154]:
# we can make set from a list
# This code converts the list into a set and removes all the duplicates from the list, while leaving only the unique values
myset = set([7, 7, 1, 2, 2, 3, 4, 3, 2])
print(myset)

{1, 2, 3, 4, 7}


### Modifying a Set
- Sets are **mutable.** However, since they are unordered, indexing has no meaning
- We cannot access or change an items/element of a set using indexing or slicing, sets does not support it!
- Eg: myset[2] will result in an error

In [155]:
# creating a set
#myset = set([92, 56, 12, 28, 37])

myset = {92, 56, 12, 28, 37}
print(myset)

# adding a single items to the set using add() method
myset.add(84)
print(myset)

# adding multiple items to the set using the update() method
myset.update([44, 53, 112])
print(myset)

# remove an element using remove() method
myset.remove(44)
print(myset)

{37, 12, 92, 56, 28}
{37, 12, 92, 84, 56, 28}
{37, 12, 44, 92, 112, 84, 53, 56, 28}
{37, 12, 92, 112, 84, 53, 56, 28}


### Python Set Operations
- The union operator **"|"** combines two sets to form a new one containing items from both
- The intersection operator **"&"** gets items common only to both
- The difference operator **"-"** gets items in the first set but not in the second
- The symmetric difference operator **"^"** gets items in either set, but not both (excluding the intersection)

![set](pics/PythonSetOperatioons.png)

In [156]:
# Let us consider the following two sets

dataScientist = {"Python", "R", "ML", "SQL", "PowerBI", "Tableau"}

dataEngineer = {"VB", "SQL", "Excel", "Hadoop", "PowerBI"}

In [157]:
# Union is performed using "|" operator
print(dataScientist | dataEngineer)

# Same can be accomplished using the union() method
print(dataScientist.union(dataEngineer))

{'Python', 'VB', 'Hadoop', 'ML', 'Excel', 'R', 'PowerBI', 'SQL', 'Tableau'}
{'Python', 'VB', 'Hadoop', 'ML', 'Excel', 'R', 'PowerBI', 'SQL', 'Tableau'}


In [158]:
# Intersection is performed using "&" operator
print(dataScientist & dataEngineer)

# Same can be accomplished using the intersection() method
print(dataScientist.intersection(dataEngineer))

{'PowerBI', 'SQL'}
{'PowerBI', 'SQL'}


In [159]:
# Difference is performed using "-" operator
print(dataScientist - dataEngineer)

#Same can be accomplished using the difference() method
print(dataScientist.difference(dataEngineer))

{'Python', 'R', 'ML', 'Tableau'}
{'Python', 'R', 'ML', 'Tableau'}


In [160]:
# Symmetric difference is performed using ^ operator
print(dataScientist ^ dataEngineer)

# Same can be accomplished using the method symmetric_difference()
print(dataScientist.symmetric_difference(dataEngineer))

{'Python', 'VB', 'Hadoop', 'ML', 'Excel', 'R', 'Tableau'}
{'Python', 'VB', 'Hadoop', 'ML', 'Excel', 'R', 'Tableau'}


## Python Set Methods

- Python has set of built-in methods that are available with every set object
- They are accessed as **set.method()**

| Method | Description   |
|:- |:- |
|add()|Adds new items to the set|
|clear()|Removes all items from the set|
|copy()|Returns a copy of the set|
|difference()|Returns a set containing the difference between two or more sets|
|difference_update()|Removes the items in this set that are also included in another, specified set|
|discard()|Removes the specified item from the set|
|intersection()|Returns a set, that is the intersection of two other sets|
|intersection_update()|Removes the items in the current set that are not present in other, specified set(s)|
|isdisjoint()|Returns whether two sets have a intersection or not - boolean answer|
|issubset()|Returns whether another set contains current set or not - boolean answer|
|issuperset()|Returns whether current set contains another set or not -- boolean answer|
|pop()|Removes items from the set|
|remove()|Removes the specified item|
|symmetric_difference()|Returns a set with the symmetric differences of two sets|
|symmetric_difference_update()|inserts the symmetric differences from this set and another|
|union()|Return a set containing the union of sets|
|update()|Update the set with the union of this set and others|



<br><br>

#### Some useful references:

[Python Set Methods](https://docs.python.org/3/tutorial/datastructures.html#sets)

[Python Set Methods](https://www.w3schools.com/python/python_ref_set.asp)



#### Question

![prodset](pics/prodset.png)

- You have been given list containing various duplicating product categories, your task is to find out only the unique product categories from the below list
- create a new variable called "uniquecat1" to save the results

In [161]:
# Write down the answer here:

# convert the following list into a set and removes all the duplicates from the list, while leaving only the unique values
category = ["Office Supplies","Technology","Office Supplies","Office Supplies","Technology","Office Supplies","Technology","Technology","Office Supplies",
"Technology","Office Supplies","Office Supplies","Technology","Office Supplies","Technology","Office Supplies","Office Supplies","Furniture",
"Office Supplies","Technology"]

uniquecat1 = set(category)

uniquecat1

{'Furniture', 'Office Supplies', 'Technology'}

#### Question

![prodcatset](pics/prodcatset.png)

- You have been given two sets containing popular product categories from UK and France
- Using these two sets carryout the following tasks

In [162]:
# Write down the answer here:

uk = set(["Office Supplies","Technology","Office Supplies","Office Supplies","Technology","Office Supplies","Toys","Technology",
"Office Supplies","Toys"])

france = set(["Office Supplies","Office Supplies","Office Supplies","Technology","Office Supplies","Office Supplies","Technology",
"Office Supplies","Furniture","Office Supplies"])

# Find out common product categories popular in both UK and France
print(uk & france)
print(uk.intersection(france))

{'Office Supplies', 'Technology'}
{'Office Supplies', 'Technology'}


In [163]:
# Find out product categories only popular in UK but not in France
print(uk - france)
print(uk.difference(france))

# Find out product categories only popular in France but not in UK
print(france - uk)
print(france.difference(uk))

{'Toys'}
{'Toys'}
{'Furniture'}
{'Furniture'}


## Dictionary
- A dictionary is a collection of items which is unordered, **mutable(changeable)** and indexed
- A dictionary is created by placing all items/elements inside **curly braces { }**, separated by commas, and each item in a dictionary has a key/value pairs
- we can also create a dictionary using the built-in dict() function
- An item has a key(unique index) and a corresponding value that is expressed as a pair (key: value)

![dict](pics/dict.png)


In [164]:
# Creating a dictionary with string keys
mydict = {"name": "Dan", "age": 28, "birth year": 1975}
print(mydict)
type(mydict)

{'name': 'Dan', 'age': 28, 'birth year': 1975}


dict

In [165]:
# Creating a dictionary with integer keys
mydict = {111: "HR", 112: "IT", 113:"Sales"}
print(mydict)
type(mydict)

{111: 'HR', 112: 'IT', 113: 'Sales'}


dict

In [166]:
# using dict()
mydict = dict({111: "HR", 112: "IT", 113:"Sales"})
print(mydict)
type(mydict)

{111: 'HR', 112: 'IT', 113: 'Sales'}


dict

### Accessing Items from Dictionary
- While indexing is used with other data types to access values, a dictionary uses keys
- Keys can be used either inside square brackets [] or with the get() method

In [167]:
mydict = {"name": "Dan", "age": 28, "birth year": 1975}

# Using square brackets [] to access item values
print(mydict["name"])
print(mydict["age"])

# Using get() method to access item values
print(mydict.get("name"))
print(mydict.get("age"))

Dan
28
Dan
28


In [168]:
# returns keys of the dictionary
mydict.keys()

dict_keys(['name', 'age', 'birth year'])

In [169]:
# returns values of the dictionary
mydict.values()

dict_values(['Dan', 28, 1975])

In [170]:
# return the dictionary's key-value pairs
mydict.items()

dict_items([('name', 'Dan'), ('age', 28), ('birth year', 1975)])

### Updating/Changing items in a Dictionary
- Dictionaries are mutable, add new items or change the value of existing items by using an assignment operator


In [171]:
mydict = {"name": "Dan", "age": 28, "birth year": 1975}

# Changing and adding Dictionary Items

# update value
mydict["age"] = 35

# update value
mydict["birth year"] = 1970
print(mydict)

# add new item
mydict["city"] = "London"
print(mydict)

{'name': 'Dan', 'age': 35, 'birth year': 1970}
{'name': 'Dan', 'age': 35, 'birth year': 1970, 'city': 'London'}


### Removing items from Dictionary
- We can remove item from a dictionary by using the pop() method. This method removes an item with the provided key and returns the value

- The popitem() method can be used to remove and return an arbitrary (key, value) item pair from the dictionary

- All the items can be removed at once, using the clear() method

- We can also use the del keyword to remove individual items or the entire dictionary itself

In [172]:
mydict = {"name": "Dan", "age": 28, "birth year": 1975}

# remove a particular item, returns its value
print(mydict.pop("name"))

# name key is removed in the output
print(mydict)

Dan
{'age': 28, 'birth year': 1975}


In [173]:
mydict = {"name": "Dan", "age": 28, "birth year": 1975}

# removes the last inserted key-value pair
print(mydict.popitem())

# last item is removed in the output
print(mydict)

('birth year', 1975)
{'name': 'Dan', 'age': 28}


In [174]:
mydict = {"name": "Dan", "age": 28, "birth year": 1975}

# remove all items
mydict.clear()
print(mydict)

{}


In [175]:
mydict = {"name": "Dan", "age": 28, "birth year": 1975}

# delete the dictionary itself
del mydict

#### Question

![dict](pics/dict2.png)

 - Write down the code to design the above dictionary data structure
 - Save the dictionary as "stock1"

In [176]:
# Write down the answer here:

stock1 = {"ID": 1, "Ticker": "AMZN", "Price": 3100}

stock1

{'ID': 1, 'Ticker': 'AMZN', 'Price': 3100}

#### Question

![dict](pics/dict3.png)

 - Write down the code to design the above dictionary data structure
 - Save the dictionary as "stock2"

In [177]:
# Write down the answer here:

stock2 = {"ID": [1,2,3], "Ticker": ["AMZN", "TSLA", "MSFT"], "Price": [3100,600,215]}

stock2

{'ID': [1, 2, 3],
 'Ticker': ['AMZN', 'TSLA', 'MSFT'],
 'Price': [3100, 600, 215]}

## Python Dictionary Methods

- Python has set of built-in methods that are available with every dictionary object
- They are accessed as **dictionary.method()**

| Method | Description   |
|:- |:- |
|   clear()  | Removes all items from dictionary|
|   copy()  | creates a copy of the current dictionary|
|fromkeys() |Returns a dictionary with the specified keys & values|
|get()|Returns the value of the specified key|
|items()|Returns a list containing a tuple for each key-value pair|
|keys()|Returns a list containing dictionary keys|
|pop()|Removes items with the specified key|
|popitem()|Removes the last inserted key-value pair|
|setdefault()|Returns the value of the specified key, If key does not exist, a new key will be inserted, with the specified value|
|update()|Updates the dictionary with the specified key-value pairs|
|values()|Returns a list of all the values in the dictionary|


<br><br>
#### Some useful references:

[Python Dictionary Methods](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

[Python Dictionary Methods](https://www.w3schools.com/python/python_dictionaries_methods.asp)

## Strings
- Strings are series/sequences of character data
- The string type in Python is called as **str**
- Strings are defined by using either single or double quotes
- Just like a list and tuple, the slicing operator **[ ]** can be used with strings
- Strings are immutable


![dict](pics/strings.png)

In [178]:
mystr1 = "python"

print(mystr1)

type(mystr1)

python


str

In [179]:
# Get the character at position 3 (Note that the first character has the position 0):
print(mystr1[2])
print(mystr1[-1])

t
n


## Python String Methods

- Python has set of built-in methods that are available with every string object
- They are accessed as **string.method()**

| Method | Description   |
|:- |:- |
|capitalize()|Converts the first character of a string to uppercase letters|
|upper()|Replaces the lowercase characters in a string with corresponding uppercase characters|
|lower()|Replaces the uppercase characters in a string with corresponding lowercase characters|
|title()|Returns the string with the first character of each word converted to uppercase|
|find()|finds the first occurrence of a substring in another string. If not found, the method returns -1|
|count()|The count() method returns the number of occurrences of a substring in the given string|
|isalpha()|returns true if all the characters in a string are alphabetic letters (a-z or A-Z), otherwise it returns false|
|isdigit()|returns true if all the characters in string are digits (0-9), if not, it returns false|
|islower()|returns true if all the characters in the string are lowercase characters, else it returns false|
|isupper()|returns true if all the characters in the string are uppercase characters, else it returns false|

<br><br>
#### Some useful references:

[Python String Methods](https://www.w3schools.com/python/python_strings_methods.asp)